# Configure H2 database
# Our code configures the H2 database connection for a Spring Boot
# application. It specifies the URL, driver class name, username,
# and password for the H2 database.
# The spring.datasource.url property sets the JDBC URL for the
# H2 database and here we use an in-memory (mem) database named
# productypedb

# JDBC Driver
# The spring.datasource.driverClassName property specifies the
# fully qualified class name of the JDBC driver to be used.
# Here, we set it to use the H2 driver:

# Username and Password
# The spring.datasource.username and spring.datasource.password
# properties specify the username and password to be used when
# connecting to the H2 database. We set the username to sa and
# the password to an empty string.

spring.datasource.url=jdbc:h2:mem:customerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Our code configures specific properties for the Java Persistence
# API (JPA) and Hibernate in a Spring Boot application.
# The spring.jpa.show-sql property is set to true, which enables
# logging of SQL statements generated by Hibernate which is useful
# when debugging and understanding the SQL queries being executed
# by the application.
# The spring.jpa.properties.hibernate.dialect property specifies
# the Hibernate dialect to be used.
# Here we set it to org.hibernate.dialect.H2Dialect, which is the
# appropriate one for the H2 database. The dialect is responsible
# for generating the correct SQL syntax for the specific database.
# The spring.jpa.hibernate.ddl-auto property is set to create which
# means that Hibernate will automatically create the database schema
# based on the entity classes. This is useful for development and
# testing but should be changed to update or none for production
# environments to avoid data loss.
# The spring.jpa.defer-datasource-initialization property is set to
# true, which defers the initialization of the data source until
# the application context has been created. This is useful when
# the data source initialization is dependent on other beans being
# created first.

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true


# Enable H2 console
# The spring.h2.console.enabled property is set to true, which enables
# the H2 console. The H2 console is a web-based database management tool
# that allows us to interact with the H2 database. It provides an
# interface for viewing and managing the database tables, executing SQL
# queries, and performing other database operations.

spring.h2.console.enabled=true

# Configure URL pattern for accessing
# The spring.h2.console.path property specifies the URL pattern for
# accessing the H2 console. By default, it is set to /h2-console, so we
# can access the H2 console at http://localhost:8080/h2-console
# But we will use h2-ui and access it at http://localhost:8080/h2-ui
# http://localhost:9999/h2-ui

spring.h2.console.path=/h2-ui


# Enabling Virtual ThreadsYou can activate this feature globally
# using a single property configuration.
# Prerequisites: Java 21 or laterSpring Boot 3.2 or later
spring.threads.virtual.enabled=true